### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by ericonr** [ftilde/unsegen_terminal#4]
Hi!

The last commit here updated the nix version, which is necessary for the crate to build on ppc. Would it be possible to make a release with that change?

**Comment by ftilde** [comment]
>The last commit here updated the nix version, which is necessary for 
>the crate to build on ppc. Would it be possible to make a release with 
>that change?
Sure, no problem. I've just uploaded version 0.2.2 to crates.io.

**Comment by ericonr** [comment]
Great, thank you!

After a `cargo update`, `ugdb` now depends on a single version of `nix` as well :)
